# Generated by Django 5.1 on 2024-09-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=350)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('prioridade', models.CharField(choices=[('Baixa', 'baixa'), ('Média', 'média'), ('Alta', 'alta')], default='Média', max_length=20)),
                ('status', models.CharField(choices=[('Pendente', 'pendente'), ('Concluído', 'concluido'), ('Adiado', 'adiado')], default='Pendente', max_length=25)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('anexos', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('tags', models.ManyToManyField(blank=True, to='app_tarefas.tag')),
            ],
            options={
                'ordering': ['-criacao'],
            },
        ),
    ]
